package com.zkhy.contest.web.dao.model;

import java.util.Date;

public class Apply {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.id
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.competition_id
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    private Long competitionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.user_id
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.accessory
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    private String accessory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.apply_time
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    private Date applyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.status
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    private Byte status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.id
     *
     * @return the value of apply.id
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.id
     *
     * @param id the value for apply.id
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.competition_id
     *
     * @return the value of apply.competition_id
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    public Long getCompetitionId() {
        return competitionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.competition_id
     *
     * @param competitionId the value for apply.competition_id
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    public void setCompetitionId(Long competitionId) {
        this.competitionId = competitionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.user_id
     *
     * @return the value of apply.user_id
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.user_id
     *
     * @param userId the value for apply.user_id
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.accessory
     *
     * @return the value of apply.accessory
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    public String getAccessory() {
        return accessory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.accessory
     *
     * @param accessory the value for apply.accessory
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    public void setAccessory(String accessory) {
        this.accessory = accessory == null ? null : accessory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.apply_time
     *
     * @return the value of apply.apply_time
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    public Date getApplyTime() {
        return applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.apply_time
     *
     * @param applyTime the value for apply.apply_time
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    public void setApplyTime(Date applyTime) {
        this.applyTime = applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.status
     *
     * @return the value of apply.status
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.status
     *
     * @param status the value for apply.status
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}