package com.zkhy.contest.web.dao.model;

import java.util.Date;

public class Competition {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competition.id
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competition.org_id
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    private Long orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competition.name
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competition.two_dimension_code
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    private String twoDimensionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competition.competition_time
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    private Date competitionTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competition.apply_end_time
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    private Date applyEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competition.create_time
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competition.status
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column competition.information
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    private String information;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competition.id
     *
     * @return the value of competition.id
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competition.id
     *
     * @param id the value for competition.id
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competition.org_id
     *
     * @return the value of competition.org_id
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competition.org_id
     *
     * @param orgId the value for competition.org_id
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competition.name
     *
     * @return the value of competition.name
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competition.name
     *
     * @param name the value for competition.name
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competition.two_dimension_code
     *
     * @return the value of competition.two_dimension_code
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    public String getTwoDimensionCode() {
        return twoDimensionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competition.two_dimension_code
     *
     * @param twoDimensionCode the value for competition.two_dimension_code
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    public void setTwoDimensionCode(String twoDimensionCode) {
        this.twoDimensionCode = twoDimensionCode == null ? null : twoDimensionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competition.competition_time
     *
     * @return the value of competition.competition_time
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    public Date getCompetitionTime() {
        return competitionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competition.competition_time
     *
     * @param competitionTime the value for competition.competition_time
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    public void setCompetitionTime(Date competitionTime) {
        this.competitionTime = competitionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competition.apply_end_time
     *
     * @return the value of competition.apply_end_time
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    public Date getApplyEndTime() {
        return applyEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competition.apply_end_time
     *
     * @param applyEndTime the value for competition.apply_end_time
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    public void setApplyEndTime(Date applyEndTime) {
        this.applyEndTime = applyEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competition.create_time
     *
     * @return the value of competition.create_time
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competition.create_time
     *
     * @param createTime the value for competition.create_time
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competition.status
     *
     * @return the value of competition.status
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competition.status
     *
     * @param status the value for competition.status
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column competition.information
     *
     * @return the value of competition.information
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    public String getInformation() {
        return information;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column competition.information
     *
     * @param information the value for competition.information
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    public void setInformation(String information) {
        this.information = information == null ? null : information.trim();
    }
}