package com.zkhy.contest.web.dao.mapper;

import com.zkhy.contest.web.dao.model.Competition;
import com.zkhy.contest.web.dao.model.CompetitionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CompetitionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competition
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    int countByExample(CompetitionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competition
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competition
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    int insert(Competition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competition
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    int insertSelective(Competition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competition
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    List<Competition> selectByExampleWithBLOBs(CompetitionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competition
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    List<Competition> selectByExample(CompetitionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competition
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    Competition selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competition
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    int updateByExampleSelective(@Param("record") Competition record, @Param("example") CompetitionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competition
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    int updateByExampleWithBLOBs(@Param("record") Competition record, @Param("example") CompetitionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competition
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    int updateByExample(@Param("record") Competition record, @Param("example") CompetitionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competition
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    int updateByPrimaryKeySelective(Competition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competition
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    int updateByPrimaryKeyWithBLOBs(Competition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table competition
     *
     * @mbggenerated Tue Nov 04 14:08:53 CST 2014
     */
    int updateByPrimaryKey(Competition record);
    
    /**
     * 返回当前表中最大id
     * @return
     */
    Long maxCompetitionId();
}